// order
export const FETCH_ORDERS_INIT = "order@FETCH_ORDERS_INIT"
export const FETCH_ORDERS_SUCCEDED = "order@FETCH_ORDERS_SUCCEDED"
export const FETCH_ORDERS_FAILED = "order@FETCH_ORDERS_FAILED"

export const CLEAR_ORDER = "order@CLEAR_ORDER"

export const CREATE_ORDER_INIT = "order@CREATE_ORDER_INIT"
export const CREATE_ORDER_SUCCEDED = "order@CREATE_ORDER_SUCCEDED"
export const CREATE_ORDER_FAILED = "order@CREATE_ORDER_FAILED"

export const FETCH_ORDER_INIT = "order@FETCH_ORDER_INIT"
export const FETCH_ORDER_SUCCEDED = "order@FETCH_ORDER_SUCCEDED"
export const FETCH_ORDER_FAILED = "order@FETCH_ORDER_FAILED"

export const EDIT_ORDER_INIT = "order@EDIT_ORDER_INIT"
export const EDIT_ORDER_SUCCEDED = "order@EDIT_ORDER_SUCCEDED"
export const EDIT_ORDER_FAILED = "order@EDIT_ORDER_FAILED"

export const DEACTIVATE_ORDER_INIT = "order@DEACTIVATE_ORDER_INIT"
export const DEACTIVATE_ORDER_SUCCEDED = "order@DEACTIVATE_ORDER_SUCCEDED"
export const DEACTIVATE_ORDER_FAILED = "order@DEACTIVATE_ORDER_FAILED"

export const ACTIVATE_ORDER_INIT = "order@ACTIVATE_ORDER_INIT"
export const ACTIVATE_ORDER_SUCCEDED = "order@ACTIVATE_ORDER_SUCCEDED"
export const ACTIVATE_ORDER_FAILED = "order@ACTIVATE_ORDER_FAILED"
