export const ORDERS = "/api/orders"
export const ORDER = "/api/orders/:param"
export const ORDER_ACTIVATE = "/api/orders/:param/activate"
export const ORDER_DEACTIVATE = "/api/orders/:param/deactivate"
export const EXPORT_ORDER = "/api/orders/export"
export const IMPORT_ORDER = "/api/orders/import"
