export const FETCH_ORDERS_INCOME_BY_DATE_INIT = "stats@FETCH_ORDERS_INCOME_BY_DATE_INIT"
export const FETCH_ORDERS_INCOME_BY_DATE_SUCCEDED = "stats@FETCH_ORDERS_INCOME_BY_DATE_SUCCEDED"
export const FETCH_ORDERS_INCOME_BY_DATE_FAILED = "stats@FETCH_ORDERS_INCOME_BY_DATE_FAILED"

export const FETCH_ORDERS_COUNT_BY_DATE_INIT = "stats@FETCH_ORDERS_COUNT_BY_DATE_INIT"
export const FETCH_ORDERS_COUNT_BY_DATE_SUCCEDED = "stats@FETCH_ORDERS_COUNT_BY_DATE_SUCCEDED"
export const FETCH_ORDERS_COUNT_BY_DATE_FAILED = "stats@FETCH_ORDERS_COUNT_BY_DATE_FAILED"

export const FETCH_ORDERS_COUNT_BY_STATUS_INIT = "stats@FETCH_ORDERS_COUNT_BY_STATUS_INIT"
export const FETCH_ORDERS_COUNT_BY_STATUS_SUCCEDED = "stats@FETCH_ORDERS_COUNT_BY_STATUS_SUCCEDED"
export const FETCH_ORDERS_COUNT_BY_STATUS_FAILED = "stats@FETCH_ORDERS_COUNT_BY_STATUS_FAILED"

export const CLEAR_STATS = "stats@CLEAR_STATS"
