// structure
export const FETCH_STRUCTURES_INIT = "structure@FETCH_STRUCTURES_INIT"
export const FETCH_STRUCTURES_SUCCEDED = "structure@FETCH_STRUCTURES_SUCCEDED"
export const FETCH_STRUCTURES_FAILED = "structure@FETCH_STRUCTURES_FAILED"

export const CLEAR_STRUCTURE_FORM = "structure@CLEAR_STRUCTURE_FORM"

export const CREATE_STRUCTURE_INIT = "structure@CREATE_STRUCTURE_INIT"
export const CREATE_STRUCTURE_SUCCEDED = "structure@CREATE_STRUCTURE_SUCCEDED"
export const CREATE_STRUCTURE_FAILED = "structure@CREATE_STRUCTURE_FAILED"

export const FETCH_STRUCTURE_INIT = "structure@FETCH_STRUCTURE_INIT"
export const FETCH_STRUCTURE_SUCCEDED = "structure@FETCH_STRUCTURE_SUCCEDED"
export const FETCH_STRUCTURE_FAILED = "structure@FETCH_STRUCTURE_FAILED"

export const EDIT_STRUCTURE_INIT = "structure@EDIT_STRUCTURE_INIT"
export const EDIT_STRUCTURE_SUCCEDED = "structure@EDIT_STRUCTURE_SUCCEDED"
export const EDIT_STRUCTURE_FAILED = "structure@EDIT_STRUCTURE_FAILED"

export const DELETE_STRUCTURE_INIT = "structure@DELETE_STRUCTURE_INIT"
export const DELETE_STRUCTURE_SUCCEDED = "structure@DELETE_STRUCTURE_SUCCEDED"
export const DELETE_STRUCTURE_FAILED = "structure@DELETE_STRUCTURE_FAILED"

// Address
export const FETCH_ADDRESSES_INIT = "address@FETCH_ADDRESSESES_INIT"
export const FETCH_ADDRESSES_SUCCEDED = "address@FETCH_ADDRESSES_SUCCEDED"
export const FETCH_ADDRESSES_FAILED = "address@FETCH_ADDRESSES_FAILED"
