// product
export const FETCH_PRODUCTS_INIT = "product@FETCH_PRODUCTS_INIT"
export const FETCH_PRODUCTS_SUCCEDED = "product@FETCH_PRODUCTS_SUCCEDED"
export const FETCH_PRODUCTS_FAILED = "product@FETCH_PRODUCTS_FAILED"

export const CLEAR_PRODUCT = "product@CLEAR_PRODUCT"

export const CREATE_PRODUCT_INIT = "product@CREATE_PRODUCT_INIT"
export const CREATE_PRODUCT_SUCCEDED = "product@CREATE_PRODUCT_SUCCEDED"
export const CREATE_PRODUCT_FAILED = "product@CREATE_PRODUCT_FAILED"

export const FETCH_PRODUCT_INIT = "product@FETCH_PRODUCT_INIT"
export const FETCH_PRODUCT_SUCCEDED = "product@FETCH_PRODUCT_SUCCEDED"
export const FETCH_PRODUCT_FAILED = "product@FETCH_PRODUCT_FAILED"

export const EDIT_PRODUCT_INIT = "product@EDIT_PRODUCT_INIT"
export const EDIT_PRODUCT_SUCCEDED = "product@EDIT_PRODUCT_SUCCEDED"
export const EDIT_PRODUCT_FAILED = "product@EDIT_PRODUCT_FAILED"

export const DEACTIVATE_PRODUCT_INIT = "product@DEACTIVATE_PRODUCT_INIT"
export const DEACTIVATE_PRODUCT_SUCCEDED = "product@DEACTIVATE_PRODUCT_SUCCEDED"
export const DEACTIVATE_PRODUCT_FAILED = "product@DEACTIVATE_PRODUCT_FAILED"

export const ACTIVATE_PRODUCT_INIT = "product@ACTIVATE_PRODUCT_INIT"
export const ACTIVATE_PRODUCT_SUCCEDED = "product@ACTIVATE_PRODUCT_SUCCEDED"
export const ACTIVATE_PRODUCT_FAILED = "product@ACTIVATE_PRODUCT_FAILED"
