export const PRODUCTS = "/api/products"
export const PRODUCT = "/api/products/:param"
export const PRODUCT_ACTIVATE = "/api/products/:param/activate"
export const PRODUCT_DEACTIVATE = "/api/products/:param/deactivate"
export const EXPORT_PRODUCT = "/api/products/export"
export const IMPORT_PRODUCT = "/api/products/import"
