export const CATEGORYS = "/api/categories"
export const CATEGORY = "/api/categories/:param"
export const CATEGORY_ACTIVATE = "/api/categories/:param/activate"
export const CATEGORY_DEACTIVATE = "/api/categories/:param/deactivate"
export const EXPORT_CATEGORY = "/api/categories/export"
export const IMPORT_CATEGORY = "/api/categories/import"
